title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-cayman

conference_name: "Navigating Large Language Models for Recommendation: From Architecture to Learning Paradigms and Deployment"
# conference_www: "on the Web Conference 2024 (WWW'24)"
conference_www: "on SIGIR 2025, July 13th, 2025"
# conference_venue: "Singapore, Monday 13 - Friday 17 May 2024"
conference_venue: "Padova Congress center"
# conference_intro: "Will be held in 2024"
conference_intro: ""

github:
  workshop_url: https://generative-rec.github.io/
  survey_url: https://generative-rec.github.io/survey/

collections:
  organizers:
    output: true
  speakers:
    output: true
